### ISSUE TITLE
Compatibility with Webpack and Babel

### ISSUE THREAD

**Issue by withgallantry** [walmartlabs/electrode-react-ssr-optimization#1]
Brilliant work. I'm currently trying to get this working on a basic level in a project with Webpack and Babel.
It's an universal app and I have babel initialised as require` ('babel-register') ({})`. Then shortly after I have the implementation of electrode-react-ssr-optimization. I then use imports instead of require.
The issue was the cache is returning 0 length and the key generator function appears to have not been called.
I believe webpack might be using it's own require code on transpilation. Was wondering if you had any experience with this before I go digging in.

**Comment by maximenajim** [comment]
Hi @withgallantry, thanks for the feedback and for trying out this library.  We do have examples internally of universal apps using this library along with Babel via require hook.   You'd might want to check if /node_modules is being ignored by Babel.  If so, would it be possible to post a simple version of the app somewhere so that I can reproduce and debug the issue you are seeing?

**Comment by withgallantry** [comment]
Hi @maximenajim, thanks for replying. I've since managed to narrow the error down to `Can't add property _instantiateReactComponent, object is not extensible`. I will get a code sample together as a next step.

**Comment by withgallantry** [comment]
Solved the issue - it was due to two different React versions. The package.json contains a reference to react and react-dom which were behind the version I was using. I've updated the package.json to remove both and rely on my listed version of react and this solved the issue.
